import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { name, email, wish, image_base64 } = await req.json();

    const trimmedName = typeof name === "string" ? name.trim() : "";
    const safeEmail = typeof email === "string" ? email.trim() : "";
    const giftWish = typeof wish === "string" ? wish.trim().slice(0, 80) : "";

    console.log("Processing elf image request for:", trimmedName, "with wish:", giftWish);

    if (!trimmedName || !image_base64) {
      throw new Error("Missing required fields: name or image_base64");
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Fixed AI prompt with gift wish embedded
    const promptText = `Transform the person into a realistic Christmas elf while preserving facial proportions and identity. Add a red elf hat, subtle elf ears, festive winter clothing. Create a warm Nordic Christmas scene with soft lighting and gentle snowfall. Incorporate the user's gift wish: '${giftWish}' into the background as tasteful festive elements (props, subtle icons, or a small elegant sign), not covering the face. High realism, no distortion, sharp details.`;

    console.log("AI prompt:", promptText);

    // Generate elf image using Lovable AI Gateway
    console.log("Calling Lovable AI for elf transformation...");
    
    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: [
              {
                type: "text",
                text: promptText,
              },
              {
                type: "image_url",
                image_url: {
                  url: image_base64,
                },
              },
            ],
          },
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error("AI Gateway error:", aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        throw new Error("Liikaa pyyntöjä, yritä hetken kuluttua uudelleen.");
      }
      if (aiResponse.status === 402) {
        throw new Error("AI-palvelun käyttöraja ylitetty.");
      }
      throw new Error(`AI generation failed: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    console.log("AI response received");

    const generatedImageBase64 = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!generatedImageBase64) {
      console.error("No image in AI response:", JSON.stringify(aiData));
      throw new Error("No image generated by AI");
    }

    // Extract base64 data and upload to storage
    const base64Data = generatedImageBase64.replace(/^data:image\/\w+;base64,/, "");
    const imageBytes = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));
    
    const fileName = `elf_${Date.now()}_${Math.random().toString(36).substring(7)}.png`;
    
    console.log("Uploading to storage:", fileName);
    
    const { error: uploadError } = await supabase.storage
      .from("elf-images")
      .upload(fileName, imageBytes, {
        contentType: "image/png",
        upsert: false,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      throw new Error("Failed to upload image");
    }

    // Get public URL
    const { data: urlData } = supabase.storage
      .from("elf-images")
      .getPublicUrl(fileName);

    const imageUrl = urlData.publicUrl;
    console.log("Image uploaded:", imageUrl);

    // Create database record (email can be null)
    const { data: record, error: dbError } = await supabase
      .from("elf_badges")
      .insert({
        name: trimmedName,
        email: safeEmail || `anon_${Date.now()}@temp.local`,
        quiz_answer: giftWish,
        elf_image_url: imageUrl,
      })
      .select()
      .single();

    if (dbError) {
      console.error("Database error:", dbError);
      throw new Error("Failed to save record");
    }

    console.log("Record created:", record.id);

    return new Response(
      JSON.stringify({
        success: true,
        image_url: imageUrl,
        id: record.id,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Error in elf-image function:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
