import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { name, email, quiz_answer, image_base64 } = await req.json();

    console.log("Processing elf image request for:", name);

    if (!name || !email || !image_base64) {
      throw new Error("Missing required fields: name, email, or image_base64");
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Build the prompt with optional gift wish
    const wish = (quiz_answer || "").trim().slice(0, 120);
    
    let promptText = "Transform this person into a friendly, cheerful Christmas elf. Add a festive red and green elf hat with a gold bell, pointed elf ears, rosy cheeks. Keep the person's face recognizable and maintain their expression. High quality, photorealistic style with warm Christmas lighting.";
    
    if (wish) {
      // Include gift wish in the scene
      promptText += ` The background and scene should subtly reflect this Christmas gift wish: "${wish}". Use it as inspiration for the environment, gifts, or atmosphere visible in the background, but keep the person clearly visible as the main subject.`;
      console.log("Including gift wish in prompt:", wish);
    } else {
      // Default snowy background
      promptText += " Use a festive snowy winter background with soft bokeh lights and warm atmosphere.";
    }

    // Generate elf image using Lovable AI Gateway
    console.log("Calling Lovable AI for elf transformation...");
    
    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: [
              {
                type: "text",
                text: promptText,
              },
              {
                type: "image_url",
                image_url: {
                  url: image_base64,
                },
              },
            ],
          },
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error("AI Gateway error:", aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        throw new Error("Liikaa pyyntöjä, yritä hetken kuluttua uudelleen.");
      }
      if (aiResponse.status === 402) {
        throw new Error("AI-palvelun käyttöraja ylitetty.");
      }
      throw new Error(`AI generation failed: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    console.log("AI response received");

    const generatedImageBase64 = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!generatedImageBase64) {
      console.error("No image in AI response:", JSON.stringify(aiData));
      throw new Error("No image generated by AI");
    }

    // Extract base64 data and upload to storage
    const base64Data = generatedImageBase64.replace(/^data:image\/\w+;base64,/, "");
    const imageBytes = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));
    
    const fileName = `elf_${Date.now()}_${Math.random().toString(36).substring(7)}.png`;
    
    console.log("Uploading to storage:", fileName);
    
    const { error: uploadError } = await supabase.storage
      .from("elf-images")
      .upload(fileName, imageBytes, {
        contentType: "image/png",
        upsert: false,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      throw new Error("Failed to upload image");
    }

    // Get public URL
    const { data: urlData } = supabase.storage
      .from("elf-images")
      .getPublicUrl(fileName);

    const imageUrl = urlData.publicUrl;
    console.log("Image uploaded:", imageUrl);

    // Create database record
    const { data: record, error: dbError } = await supabase
      .from("elf_badges")
      .insert({
        name,
        email,
        quiz_answer,
        elf_image_url: imageUrl,
      })
      .select()
      .single();

    if (dbError) {
      console.error("Database error:", dbError);
      throw new Error("Failed to save record");
    }

    console.log("Record created:", record.id);

    return new Response(
      JSON.stringify({
        success: true,
        image_url: imageUrl,
        id: record.id,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Error in elf-image function:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
